name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Format
        run: cargo fmt --verbose --check
      - name: Generate docs
        run: cargo doc --verbose
      - name: Run tests
        run: cargo test --verbose
  fuzz:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["generation_guard", "flag_guard", "no_guard"]
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly
      - run: cargo install cargo-fuzz
      - name: Fuzz ${{ matrix.target }}
        run: cargo +nightly fuzz run ${{ matrix.target }} -- -runs=500000
